/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    Greet: typeof import('./src/components/Greet.vue')['default']
    LeftBanner: typeof import('./src/components/LeftBanner.vue')['default']
    MenuBar: typeof import('./src/components/MenuBar.vue')['default']
    TestFile: typeof import('./src/components/TestFile.vue')['default']
  }
}
